# Theme Settings
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"

# Site Settings
title                    : "Grilled Potato Docs"
title_separator          : "-"
name                     : "Grilled Potato"
description              : "A public website for a self-study project in AI/ML."
url                      : "https://grilled-potato.github.io/"
repository               : "grilled-potato/grilled-potato.github.io"
words_per_minute         : 200
search                   : true

# Site Author
author:
  name                   : "Grilled Potato"
  avatar                 : "/assets/images/bio-photo.jpg"
  bio                    : "I am a grilled potato."
  location               : "Singapore"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/grilled-potato"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/grilled-potato"

# Reading Files
include:
  - _pages

# Conversion
markdown: kramdown

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Singapore

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

